### ISSUE TITLE
Can't connect to lotus RPC 

### ISSUE THREAD

**Issue by rasha08** [jimpick/lotus-fvm-localnet#1]
# Unable to connect to lotus rpc

### Daemon
```sh
docker run -p 1234:1234  -i -t --rm --name lotus-fvm-localnet ghcr.io/jimpick/lotus-fvm-localnet-ready:latest lotus daemon --lotus-make-genesis=devgen.car --genesis-template=localnet.json --bootstrap=false
```

### Miner
```sh
docker exec -i -t lotus-fvm-localnet lotus-miner run --nosync
```

###
```sh
curl http://0.0.0.0:1234
     curl: (52) Empty reply from server

```

## Expected behavior 
- User should be able to consume lotus rpc.

**Comment by jimpick** [comment]
I am using these images as a base which I add some additional tools to in this repo:

* https://github.com/jimpick/lotus-fvm-localnet-web

The images built in that repo add a Caddy webserver to reverse proxy to the API + add CORS headers so it can be used from web applications. It also adds some other tools and source code that I use in the interactive FVM demo notebooks here:

* https://observablehq.com/collection/@jimpick/filecoin-virtual-machine

It might be a simple thing to add an EXPOSE line to the Dockerfile in this repo to expose port 1234. I'll try it out to see if it's easy to add.

**Comment by jimpick** [comment]
I've updated the images to expose port 1234 and the README now has a curl example. :-)
